// Generated by clap-gen. DO NOT EDIT.
#include "clapgen_metadata.hpp"

namespace clapgen::generated {

const PluginMetadata plugin{"com.example.codegen", "Codegen", "Example", "1.0.0", nullptr, nullptr, nullptr, nullptr, ""};

const ProcessorMetadata processor{"CodegenProcessor", ""};

const std::array<ParameterMetadata, 0> parameters{};

const std::array<AudioPortMetadata, 0> audio_ports{};

const std::array<NotePortMetadata, 0> note_ports{};

const std::array<NoteNameMetadata, 0> note_names{};

const std::array<StateFieldMetadata, 0> state_fields{};

const std::array<GuiApiMetadata, 0> gui_apis{};

const std::array<PresetLocationMetadata, 0> preset_locations{};

const std::array<PresetFormatMetadata, 0> preset_formats{};

const std::array<FactoryMetadata, 0> factories{};

const std::array<ExtensionMetadata, 0> extensions{};

} // namespace clapgen::generated
