// Generated by clap-gen. DO NOT EDIT.
#pragma once

#include <array>

namespace clapgen::generated {

struct ResourceMetadata {
    const char* path;
    const char* mime;
};

inline constexpr std::array<ResourceMetadata, 1> resources{{
    ResourceMetadata{"assets/panel.svg", "image/svg+xml"},
}};

} // namespace clapgen::generated
