use std::fmt::Write as _;

use crate::ir::{CanonicalIr, PluginIr};

use super::cpp_literal;

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header(ir: &CanonicalIr) -> String {
    header_for_plugins(std::slice::from_ref(ir.plugin()))
        .expect("a canonical plugin descriptor must satisfy descriptor collection invariants")
}

pub(crate) fn header_for_plugins(plugins: &[PluginIr]) -> Result<String, String> {
    for plugin in plugins {
        validate_plugin_c_strings(plugin)?;
    }

    let mut plugins = plugins.iter().collect::<Vec<_>>();
    plugins.sort_by(|left, right| left.id.cmp(&right.id));
    if let Some(duplicate) = plugins.windows(2).find(|pair| pair[0].id == pair[1].id) {
        return Err(format!(
            "duplicate plugin descriptor ID `{}`; plugin IDs must be unique within a bundle",
            duplicate[0].id
        ));
    }

    let mut output = String::from(BANNER);
    output.push_str(
        "#pragma once\n\n#include <clap/clap.h>\n#include <cstdint>\n\nnamespace clapgen::generated {\n\n",
    );

    for (index, plugin) in plugins.iter().enumerate() {
        render_feature_array(&mut output, index, plugin);
        render_descriptor(&mut output, index, plugin);
    }
    render_descriptor_table(&mut output, plugins.len());
    output.push_str("\n} // namespace clapgen::generated\n");
    Ok(output)
}

fn validate_plugin_c_strings(plugin: &PluginIr) -> Result<(), String> {
    for (field, value) in [
        ("id", Some(plugin.id.as_str())),
        ("name", Some(plugin.name.as_str())),
        ("vendor", Some(plugin.vendor.as_str())),
        ("version", Some(plugin.version.as_str())),
        ("url", plugin.url.as_deref()),
        ("manual-url", plugin.manual_url.as_deref()),
        ("support-url", plugin.support_url.as_deref()),
        ("description", plugin.description.as_deref()),
    ] {
        if value.is_some_and(|value| value.contains('\0')) {
            return Err(format!(
                "plugin descriptor field `{field}` contains an embedded NUL character"
            ));
        }
    }

    if plugin.features.iter().any(|feature| feature.contains('\0')) {
        return Err("plugin descriptor feature contains an embedded NUL character".to_owned());
    }

    Ok(())
}

fn render_feature_array(output: &mut String, index: usize, plugin: &PluginIr) {
    writeln!(output, "inline constexpr const char* const plugin_features_{index}[] = {{")
        .expect("writing to String cannot fail");
    for feature in &plugin.features {
        writeln!(output, "    {},", cpp_literal::utf8_c_string(feature))
            .expect("writing to String cannot fail");
    }
    output.push_str("    nullptr,\n};\n\n");
}

fn render_descriptor(output: &mut String, index: usize, plugin: &PluginIr) {
    writeln!(output, "inline constexpr clap_plugin_descriptor_t plugin_descriptor_{index}{{")
        .expect("writing to String cannot fail");
    output.push_str("    .clap_version = CLAP_VERSION,\n");
    writeln!(output, "    .id = {},", cpp_literal::utf8_c_string(&plugin.id))
        .expect("writing to String cannot fail");
    writeln!(output, "    .name = {},", cpp_literal::utf8_c_string(&plugin.name))
        .expect("writing to String cannot fail");
    writeln!(output, "    .vendor = {},", cpp_literal::utf8_c_string(&plugin.vendor))
        .expect("writing to String cannot fail");
    writeln!(output, "    .url = {},", cpp_literal::optional_utf8_c_string(plugin.url.as_deref()))
        .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .manual_url = {},",
        cpp_literal::optional_utf8_c_string(plugin.manual_url.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .support_url = {},",
        cpp_literal::optional_utf8_c_string(plugin.support_url.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(output, "    .version = {},", cpp_literal::utf8_c_string(&plugin.version))
        .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .description = {},",
        cpp_literal::optional_utf8_c_string(plugin.description.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(output, "    .features = plugin_features_{index},")
        .expect("writing to String cannot fail");
    output.push_str("};\n\n");
}

fn render_descriptor_table(output: &mut String, count: usize) {
    output.push_str(
        "inline constexpr const clap_plugin_descriptor_t* const plugin_descriptors[] = {\n",
    );
    if count == 0 {
        output.push_str("    nullptr,\n");
    } else {
        for index in 0..count {
            writeln!(output, "    &plugin_descriptor_{index},")
                .expect("writing to String cannot fail");
        }
    }
    output.push_str("};\n");
    writeln!(output, "inline constexpr std::uint32_t plugin_descriptor_count = {count}u;")
        .expect("writing to String cannot fail");
}
