use std::fmt::Write as _;

use crate::ir::{CanonicalIr, PluginIr};

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header(ir: &CanonicalIr) -> String {
    header_for_plugins(std::slice::from_ref(ir.plugin()))
}

pub(crate) fn header_for_plugins(plugins: &[PluginIr]) -> String {
    let mut plugins = plugins.iter().collect::<Vec<_>>();
    plugins.sort_by(|left, right| left.id.cmp(&right.id));

    let mut output = String::from(BANNER);
    output.push_str(
        "#pragma once\n\n#include <clap/clap.h>\n#include <cstdint>\n\nnamespace clapgen::generated {\n\n",
    );

    for (index, plugin) in plugins.iter().enumerate() {
        render_feature_array(&mut output, index, plugin);
        render_descriptor(&mut output, index, plugin);
    }
    render_descriptor_table(&mut output, plugins.len());
    output.push_str("\n} // namespace clapgen::generated\n");
    output
}

fn render_feature_array(output: &mut String, index: usize, plugin: &PluginIr) {
    writeln!(
        output,
        "inline constexpr const char* const plugin_features_{index}[] = {{"
    )
    .expect("writing to String cannot fail");
    for feature in &plugin.features {
        writeln!(output, "    {},", cpp_string(feature)).expect("writing to String cannot fail");
    }
    output.push_str("    nullptr,\n};\n\n");
}

fn render_descriptor(output: &mut String, index: usize, plugin: &PluginIr) {
    writeln!(output, "inline constexpr clap_plugin_descriptor_t plugin_descriptor_{index}{{")
        .expect("writing to String cannot fail");
    output.push_str("    .clap_version = CLAP_VERSION,\n");
    writeln!(output, "    .id = {},", cpp_string(&plugin.id)).expect("writing to String cannot fail");
    writeln!(output, "    .name = {},", cpp_string(&plugin.name))
        .expect("writing to String cannot fail");
    writeln!(output, "    .vendor = {},", cpp_string(&plugin.vendor))
        .expect("writing to String cannot fail");
    writeln!(output, "    .url = {},", optional_cpp_string(plugin.url.as_deref()))
        .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .manual_url = {},",
        optional_cpp_string(plugin.manual_url.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .support_url = {},",
        optional_cpp_string(plugin.support_url.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(output, "    .version = {},", cpp_string(&plugin.version))
        .expect("writing to String cannot fail");
    writeln!(
        output,
        "    .description = {},",
        optional_cpp_string(plugin.description.as_deref())
    )
    .expect("writing to String cannot fail");
    writeln!(output, "    .features = plugin_features_{index},")
        .expect("writing to String cannot fail");
    output.push_str("};\n\n");
}

fn render_descriptor_table(output: &mut String, count: usize) {
    output.push_str(
        "inline constexpr const clap_plugin_descriptor_t* const plugin_descriptors[] = {\n",
    );
    if count == 0 {
        output.push_str("    nullptr,\n");
    } else {
        for index in 0..count {
            writeln!(output, "    &plugin_descriptor_{index},")
                .expect("writing to String cannot fail");
        }
    }
    output.push_str("};\n");
    writeln!(output, "inline constexpr std::uint32_t plugin_descriptor_count = {count}u;")
        .expect("writing to String cannot fail");
}

fn optional_cpp_string(value: Option<&str>) -> String {
    value.map_or_else(|| "nullptr".to_owned(), cpp_string)
}

fn cpp_string(value: &str) -> String {
    let mut output = String::with_capacity(value.len() + 2);
    output.push('"');
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{0008}' => output.push_str("\\b"),
            '\u{000C}' => output.push_str("\\f"),
            character if character.is_control() && u32::from(character) <= 0o377 => {
                write!(&mut output, "\\{:03o}", u32::from(character))
                    .expect("writing to String cannot fail");
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}
