const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn source() -> String {
    format!(
        "{BANNER}\n#include <clap/clap.h>\n\n#include \"clapgen_descriptors.hpp\"\n#include \"clapgen_instance_backend.hpp\"\n"
    )
}
