const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn source() -> String {
    format!(
        "{BANNER}\n#include <clap/clap.h>\n#include <cstdint>\n\n#include \"clapgen_descriptors.hpp\"\n#include \"clapgen_instance_backend.hpp\"\n\nnamespace clapgen::generated::detail {{\n\nbool CLAP_ABI entry_init(const char* plugin_path);\nvoid CLAP_ABI entry_deinit();\nconst void* CLAP_ABI entry_get_factory(const char* factory_id);\n\nstd::uint32_t CLAP_ABI factory_get_plugin_count(const clap_plugin_factory_t* factory);\nconst clap_plugin_descriptor_t* CLAP_ABI factory_get_plugin_descriptor(\n    const clap_plugin_factory_t* factory,\n    std::uint32_t index);\nconst clap_plugin_t* CLAP_ABI factory_create_plugin(\n    const clap_plugin_factory_t* factory,\n    const clap_host_t* host,\n    const char* plugin_id);\n\n}} // namespace clapgen::generated::detail\n"
    )
}
