use std::fmt::Write as _;

use crate::ir::CanonicalIr;

use super::cpp_literal;

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

#[derive(Clone, Copy)]
pub(crate) struct OwnedPluginExtension<'a> {
    pub(crate) id: &'a str,
    pub(crate) table_symbol: &'a str,
}

pub(crate) fn header(_ir: &CanonicalIr) -> String {
    header_for_owned_bindings(&[])
}

pub(crate) fn header_for_owned_bindings(bindings: &[OwnedPluginExtension<'_>]) -> String {
    let mut owned = bindings.to_vec();
    owned.sort_by(|left, right| left.id.cmp(right.id));

    let mut storage = String::new();
    let binding_pointer = if owned.is_empty() {
        "nullptr"
    } else {
        storage.push_str(
            "inline constinit const PluginExtensionBinding plugin_extension_bindings[] = {\n",
        );
        for binding in &owned {
            let id = cpp_literal::utf8_c_string(binding.id);
            writeln!(&mut storage, "    {{{id}, &{}}},", binding.table_symbol)
                .expect("writing to String cannot fail");
        }
        storage.push_str("};\n\n");
        "plugin_extension_bindings"
    };
    let count = owned.len();

    format!(
        "{BANNER}\n#pragma once\n\n#include <cstdint>\n#include <cstring>\n\nnamespace clapgen::generated::detail {{\n\nstruct PluginExtensionBinding {{\n    const char* id;\n    const void* table;\n}};\n\ninline const void* lookup_plugin_extension(\n    const PluginExtensionBinding* bindings,\n    std::uint32_t count,\n    const char* extension_id) noexcept {{\n    if (bindings == nullptr || extension_id == nullptr) {{\n        return nullptr;\n    }}\n    for (std::uint32_t index = 0; index < count; ++index) {{\n        if (bindings[index].id != nullptr &&\n            std::strcmp(extension_id, bindings[index].id) == 0) {{\n            return bindings[index].table;\n        }}\n    }}\n    return nullptr;\n}}\n\n// Extension declarations are not implementation ownership. Later capability generators\n// append bindings only when they emit the complete native clap_plugin_*_t table.\n{storage}inline constexpr std::uint32_t plugin_extension_count = {count}u;\n\ninline const void* generated_plugin_extension(const char* extension_id) noexcept {{\n    return lookup_plugin_extension({binding_pointer}, plugin_extension_count, extension_id);\n}}\n\n}} // namespace clapgen::generated::detail\n"
    )
}
