use crate::ir::CanonicalIr;

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header(_ir: &CanonicalIr) -> String {
    format!(
        "{BANNER}\n#pragma once\n\n#include <cstdint>\n#include <cstring>\n\nnamespace clapgen::generated::detail {{\n\nstruct PluginExtensionBinding {{\n    const char* id;\n    const void* table;\n}};\n\ninline const void* lookup_plugin_extension(\n    const PluginExtensionBinding* bindings,\n    std::uint32_t count,\n    const char* extension_id) noexcept {{\n    if (extension_id == nullptr) {{\n        return nullptr;\n    }}\n    for (std::uint32_t index = 0; index < count; ++index) {{\n        if (bindings[index].id != nullptr &&\n            std::strcmp(extension_id, bindings[index].id) == 0) {{\n            return bindings[index].table;\n        }}\n    }}\n    return nullptr;\n}}\n\n// Extension declarations are not implementation ownership. Later capability generators\n// append bindings only when they emit the complete native clap_plugin_*_t table.\ninline constexpr std::uint32_t plugin_extension_count = 0u;\n\ninline const void* generated_plugin_extension(const char* extension_id) noexcept {{\n    return lookup_plugin_extension(nullptr, plugin_extension_count, extension_id);\n}}\n\n}} // namespace clapgen::generated::detail\n"
    )
}
