use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::ir::{CanonicalIr, PersistentIdIr};

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header(ir: &CanonicalIr) -> String {
    let mut output = String::from(BANNER);
    output.push_str("#pragma once\n\n#include <clap/clap.h>\n\nnamespace clapgen::generated::ids {\n");

    let mut by_kind = BTreeMap::<&str, Vec<&PersistentIdIr>>::new();
    for id in ir.persistent_ids() {
        by_kind.entry(&id.kind).or_default().push(id);
    }

    for (kind, mut ids) in by_kind {
        ids.sort_by(|left, right| (left.value, &left.key).cmp(&(right.value, &right.key)));
        writeln!(&mut output, "\nnamespace kind_{} {{", cpp_identifier_fragment(kind))
            .expect("writing to String cannot fail");
        for id in ids {
            writeln!(
                &mut output,
                "inline constexpr clap_id id_{} = {}u;",
                cpp_identifier_fragment(&id.key),
                id.value
            )
            .expect("writing to String cannot fail");
        }
        output.push_str("} // namespace\n");
    }

    output.push_str("\n} // namespace clapgen::generated::ids\n");
    output
}

fn cpp_identifier_fragment(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    for byte in value.as_bytes() {
        if byte.is_ascii_alphanumeric() {
            output.push(char::from(*byte));
        } else {
            write!(&mut output, "_{byte:02X}").expect("writing to String cannot fail");
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::cpp_identifier_fragment;

    #[test]
    fn identifier_encoding_is_portable_and_injective_for_punctuation() {
        assert_eq!("main_2Din", cpp_identifier_fragment("main-in"));
        assert_eq!("main_5Fin", cpp_identifier_fragment("main_in"));
        assert_eq!("caf_C3_A9", cpp_identifier_fragment("café"));
    }
}
