const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header() -> String {
    format!(
        "{BANNER}\n#pragma once\n\n#include <clap/clap.h>\n#include <cstdint>\n\nnamespace clapgen::generated::detail {{\n\nconst clap_plugin_t* create_plugin_instance(\n    std::uint32_t descriptor_index,\n    const clap_host_t* host) noexcept;\n\n}} // namespace clapgen::generated::detail\n"
    )
}

pub(crate) fn source() -> String {
    format!(
        "{BANNER}\n#include \"clapgen_instance_backend.hpp\"\n\nnamespace clapgen::generated::detail {{\n\nconst clap_plugin_t* create_plugin_instance(std::uint32_t, const clap_host_t*) noexcept {{\n    return nullptr;\n}}\n\n}} // namespace clapgen::generated::detail\n"
    )
}
