use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::ir::{CanonicalIr, ExtensionIr};

use super::cpp_literal::string as cpp_string;

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";
const TYPE_DECLARATIONS: &str = "\nnamespace clapgen::generated {\n\n\
struct PluginMetadata {\n\
    const char* id;\n\
    const char* name;\n\
    const char* vendor;\n\
    const char* version;\n\
    const char* url;\n\
    const char* manual_url;\n\
    const char* support_url;\n\
    const char* description;\n\
    const char* features;\n\
};\n\n\
struct ProcessorMetadata {\n\
    const char* class_name;\n\
    const char* features;\n\
};\n\n\
struct ParameterMetadata {\n\
    const char* id;\n\
    const char* name;\n\
    double min;\n\
    double max;\n\
    double default_value;\n\
    const char* flags;\n\
    const char* unit;\n\
    bool has_steps;\n\
    std::uint64_t steps;\n\
};\n\n\
struct AudioPortMetadata {\n\
    const char* id;\n\
    const char* name;\n\
    const char* direction;\n\
    std::uint32_t channels;\n\
    const char* port_type;\n\
    const char* flags;\n\
    const char* in_place_pair;\n\
};\n\n\
struct NotePortMetadata {\n\
    const char* id;\n\
    const char* name;\n\
    const char* direction;\n\
    const char* dialects;\n\
    const char* preferred;\n\
};\n\n\
struct NoteNameMetadata {\n\
    const char* name;\n\
    bool has_key;\n\
    std::int32_t key;\n\
    bool has_channel;\n\
    std::int32_t channel;\n\
    const char* port;\n\
};\n\n\
struct StateFieldMetadata {\n\
    const char* name;\n\
    const char* field_type;\n\
    const char* default_value;\n\
    const char* tag;\n\
};\n\n\
struct GuiApiMetadata {\n\
    const char* name;\n\
    bool floating;\n\
    bool embedded;\n\
};\n\n\
struct PresetLocationMetadata {\n\
    const char* name;\n\
    const char* kind;\n\
    const char* path;\n\
};\n\n\
struct PresetFormatMetadata {\n\
    const char* name;\n\
    const char* extension;\n\
    const char* mime;\n\
};\n\n\
struct FactoryMetadata {\n\
    const char* id;\n\
    const char* kind;\n\
};\n\n\
struct ExtensionMetadata {\n\
    const char* id;\n\
    const char* version;\n\
    bool draft;\n\
    const char* header;\n\
};\n\n";

pub(crate) fn header(ir: &CanonicalIr) -> String {
    let mut output = String::from(BANNER);
    output.push_str("#pragma once\n\n#include <array>\n#include <cstdint>\n");
    for header in capability_headers(ir) {
        writeln!(&mut output, "#include <{header}>").expect("writing to String cannot fail");
    }
    output.push_str(TYPE_DECLARATIONS);
    append_array_declarations(&mut output, ir);
    output.push_str("\n} // namespace clapgen::generated\n");
    output
}

fn append_array_declarations(output: &mut String, ir: &CanonicalIr) {
    output.push_str(
        "extern const PluginMetadata plugin;\nextern const ProcessorMetadata processor;\n",
    );
    append_array_declaration(output, "ParameterMetadata", "parameters", ir.parameters().len());
    append_array_declaration(output, "AudioPortMetadata", "audio_ports", ir.audio_ports().len());
    append_array_declaration(output, "NotePortMetadata", "note_ports", ir.note_ports().len());
    append_array_declaration(output, "NoteNameMetadata", "note_names", ir.note_names().len());
    append_array_declaration(output, "StateFieldMetadata", "state_fields", ir.state_fields().len());
    append_array_declaration(output, "GuiApiMetadata", "gui_apis", ir.gui_apis().len());
    append_array_declaration(
        output,
        "PresetLocationMetadata",
        "preset_locations",
        ir.preset_locations().len(),
    );
    append_array_declaration(
        output,
        "PresetFormatMetadata",
        "preset_formats",
        ir.preset_formats().len(),
    );
    append_array_declaration(output, "FactoryMetadata", "factories", ir.factories().len());
    append_array_declaration(
        output,
        "ExtensionMetadata",
        "extensions",
        ir.stable_extension_items().len() + ir.draft_extension_items().len(),
    );
}

fn append_array_declaration(output: &mut String, type_name: &str, name: &str, count: usize) {
    writeln!(output, "extern const std::array<{type_name}, {count}> {name};")
        .expect("writing to String cannot fail");
}

pub(crate) fn source(ir: &CanonicalIr) -> String {
    let mut output = String::from(BANNER);
    output.push_str("#include \"clapgen_metadata.hpp\"\n\nnamespace clapgen::generated {\n\n");
    output.push_str(&render_plugin(ir));
    output.push_str(&render_processor(ir));
    output.push_str(&render_parameters(ir));
    output.push_str(&render_audio_ports(ir));
    output.push_str(&render_note_ports(ir));
    output.push_str(&render_note_names(ir));
    output.push_str(&render_state_fields(ir));
    output.push_str(&render_gui_apis(ir));
    output.push_str(&render_preset_locations(ir));
    output.push_str(&render_preset_formats(ir));
    output.push_str(&render_factories(ir));
    output.push_str(&render_extensions(ir));
    output.push_str("} // namespace clapgen::generated\n");
    output
}

fn capability_headers(ir: &CanonicalIr) -> BTreeSet<&'static str> {
    ir.stable_extension_items()
        .iter()
        .chain(ir.draft_extension_items())
        .filter_map(|extension| extension.header)
        .collect()
}

fn render_plugin(ir: &CanonicalIr) -> String {
    let plugin = ir.plugin();
    format!(
        "const PluginMetadata plugin{{{}, {}, {}, {}, {}, {}, {}, {}, {}}};\n\n",
        cpp_string(&plugin.id),
        cpp_string(&plugin.name),
        cpp_string(&plugin.vendor),
        cpp_string(&plugin.version),
        optional_cpp_string(plugin.url.as_deref()),
        optional_cpp_string(plugin.manual_url.as_deref()),
        optional_cpp_string(plugin.support_url.as_deref()),
        optional_cpp_string(plugin.description.as_deref()),
        cpp_string(&plugin.features.join(",")),
    )
}

fn render_processor(ir: &CanonicalIr) -> String {
    let processor = ir.processor();
    format!(
        "const ProcessorMetadata processor{{{}, {}}};\n\n",
        cpp_string(&processor.class),
        cpp_string(&processor.features.join(",")),
    )
}

fn render_parameters(ir: &CanonicalIr) -> String {
    let items = ir
        .parameters()
        .iter()
        .map(|parameter| {
            format!(
                "    ParameterMetadata{{{}, {}, {}, {}, {}, {}, {}, {}, {}}},",
                cpp_string(&parameter.id),
                cpp_string(&parameter.name),
                parameter.min,
                parameter.max,
                parameter.default,
                cpp_string(&parameter.flags.join(",")),
                optional_cpp_string(parameter.unit.as_deref()),
                parameter.steps.is_some(),
                parameter.steps.unwrap_or_default(),
            )
        })
        .collect::<Vec<_>>();
    render_array("ParameterMetadata", "parameters", &items)
}

fn render_audio_ports(ir: &CanonicalIr) -> String {
    let items = ir
        .audio_ports()
        .iter()
        .map(|port| {
            format!(
                "    AudioPortMetadata{{{}, {}, {}, {}, {}, {}, {}}},",
                cpp_string(&port.id),
                cpp_string(&port.name),
                cpp_string(port.direction.as_str()),
                port.channels,
                optional_cpp_string(port.port_type.as_deref()),
                cpp_string(&port.flags.join(",")),
                optional_cpp_string(port.in_place_pair.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("AudioPortMetadata", "audio_ports", &items)
}

fn render_note_ports(ir: &CanonicalIr) -> String {
    let items = ir
        .note_ports()
        .iter()
        .map(|port| {
            format!(
                "    NotePortMetadata{{{}, {}, {}, {}, {}}},",
                cpp_string(&port.id),
                cpp_string(&port.name),
                cpp_string(port.direction.as_str()),
                cpp_string(&port.dialects.join(",")),
                optional_cpp_string(port.preferred.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("NotePortMetadata", "note_ports", &items)
}

fn render_note_names(ir: &CanonicalIr) -> String {
    let items = ir
        .note_names()
        .iter()
        .map(|note| {
            format!(
                "    NoteNameMetadata{{{}, {}, {}, {}, {}, {}}},",
                cpp_string(&note.name),
                note.key.is_some(),
                note.key.unwrap_or_default(),
                note.channel.is_some(),
                note.channel.unwrap_or_default(),
                optional_cpp_string(note.port.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("NoteNameMetadata", "note_names", &items)
}

fn render_state_fields(ir: &CanonicalIr) -> String {
    let items = ir
        .state_fields()
        .iter()
        .map(|field| {
            format!(
                "    StateFieldMetadata{{{}, {}, {}, {}}},",
                cpp_string(&field.name),
                cpp_string(&field.field_type),
                optional_cpp_string(field.default.as_deref()),
                optional_cpp_string(field.tag.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("StateFieldMetadata", "state_fields", &items)
}

fn render_gui_apis(ir: &CanonicalIr) -> String {
    let items = ir
        .gui_apis()
        .iter()
        .map(|api| {
            format!(
                "    GuiApiMetadata{{{}, {}, {}}},",
                cpp_string(&api.name),
                api.floating,
                api.embedded,
            )
        })
        .collect::<Vec<_>>();
    render_array("GuiApiMetadata", "gui_apis", &items)
}

fn render_preset_locations(ir: &CanonicalIr) -> String {
    let items = ir
        .preset_locations()
        .iter()
        .map(|location| {
            format!(
                "    PresetLocationMetadata{{{}, {}, {}}},",
                cpp_string(&location.name),
                optional_cpp_string(location.kind.as_deref()),
                optional_cpp_string(location.path.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("PresetLocationMetadata", "preset_locations", &items)
}

fn render_preset_formats(ir: &CanonicalIr) -> String {
    let items = ir
        .preset_formats()
        .iter()
        .map(|format| {
            format!(
                "    PresetFormatMetadata{{{}, {}, {}}},",
                cpp_string(&format.name),
                optional_cpp_string(format.extension.as_deref()),
                optional_cpp_string(format.mime.as_deref()),
            )
        })
        .collect::<Vec<_>>();
    render_array("PresetFormatMetadata", "preset_formats", &items)
}

fn render_factories(ir: &CanonicalIr) -> String {
    let items = ir
        .factories()
        .iter()
        .map(|factory| {
            format!(
                "    FactoryMetadata{{{}, {}}},",
                cpp_string(&factory.id),
                cpp_string(&factory.kind),
            )
        })
        .collect::<Vec<_>>();
    render_array("FactoryMetadata", "factories", &items)
}

fn render_extensions(ir: &CanonicalIr) -> String {
    let mut extensions = ir
        .stable_extension_items()
        .iter()
        .map(|extension| (false, extension))
        .chain(ir.draft_extension_items().iter().map(|extension| (true, extension)))
        .collect::<Vec<_>>();
    extensions.sort_by(|(left_draft, left), (right_draft, right)| {
        (left_draft, &left.id, &left.version).cmp(&(right_draft, &right.id, &right.version))
    });
    let items = extensions
        .into_iter()
        .map(|(draft, extension)| render_extension(extension, draft))
        .collect::<Vec<_>>();
    render_array("ExtensionMetadata", "extensions", &items)
}

fn render_extension(extension: &ExtensionIr, draft: bool) -> String {
    format!(
        "    ExtensionMetadata{{{}, {}, {}, {}}},",
        cpp_string(&extension.id),
        optional_cpp_string(extension.version.as_deref()),
        draft,
        optional_cpp_string(extension.header),
    )
}

fn render_array(type_name: &str, name: &str, items: &[String]) -> String {
    if items.is_empty() {
        return format!("const std::array<{type_name}, 0> {name}{{}};\n\n");
    }
    format!(
        "const std::array<{type_name}, {}> {name}{{{{\n{}\n}}}};\n\n",
        items.len(),
        items.join("\n"),
    )
}

fn optional_cpp_string(value: Option<&str>) -> String {
    value.map_or_else(|| "nullptr".to_owned(), cpp_string)
}
