#![allow(dead_code)]

mod outputs;
mod render;

pub(crate) use outputs::{GeneratedFile, GenerationPlan, OUTPUT_NAMES};

pub(crate) fn render(ir: &crate::ir::CanonicalIr) -> GenerationPlan {
    render::render(ir)
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::ir::build_ir;
    use crate::metadata::parse_metadata;

    use super::{GenerationPlan, OUTPUT_NAMES, render};

    const SOURCE: &str = "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen\" vendor=\"Example\" version=\"1.0.0\"\nprocessor class=\"CodegenProcessor\"\nparameters {}\naudio-ports {}\nnote-ports {}\nstate {}\ngui {}\npresets {}\nfactories {}\nextensions {}\n";

    const RICH_SOURCE: &str = "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen \\\"Unit\\\"\" vendor=\"Example\\\\Labs\" version=\"1.0.0\" features=\"instrument,synthesizer\"\nprocessor class=\"CodegenProcessor\"\nparameters { param \"Gain\" id=\"gain\" min=0 max=1 default=0.5 flags=\"automatable\" unit=\"dB\" }\naudio-ports { input \"Main In\" id=\"main-in\" channels=2 flags=\"main\"; output \"Main Out\" id=\"main-out\" channels=2 flags=\"main\" }\nnote-ports { input \"Notes\" id=\"notes\" dialects=\"clap,midi\" preferred=\"clap\" }\nstate { field \"mode\" type=\"integer\" default=0 tag=\"mode\" }\ngui {}\npresets {}\nfactories {}\nextensions { enable \"clap.params\" }\n";

    fn ir_from(source: &str) -> crate::ir::CanonicalIr {
        let path = Path::new("plugin.kdl");
        let metadata = parse_metadata(path, source).expect("metadata should parse");
        build_ir(path, source, &metadata).expect("canonical IR should build")
    }

    fn generated_text<'a>(plan: &'a GenerationPlan, path: &str) -> &'a str {
        let file = plan.files.iter().find(|file| file.path == path).expect("generated file");
        std::str::from_utf8(&file.bytes).expect("generated files must be UTF-8")
    }

    #[test]
    fn fixed_output_contract_is_stable() {
        assert_eq!(
            OUTPUT_NAMES,
            &[
                "clapgen.d",
                "clapgen.manifest.kdl",
                "clapgen.sources.kdl",
                "clapgen_metadata.cpp",
                "clapgen_metadata.hpp",
                "clapgen_resources.hpp",
            ]
        );
        assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("entry")));
        assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("factory")));
        assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("plugin.cpp")));
    }

    #[test]
    fn canonical_ir_renders_to_a_pure_deterministic_plan() {
        let ir = ir_from(SOURCE);
        let first = render(&ir);
        let second = render(&ir);
        let paths = first.files.iter().map(|file| file.path).collect::<Vec<_>>();

        assert_eq!(first, second);
        assert_eq!(paths.as_slice(), OUTPUT_NAMES);
    }

    #[test]
    fn metadata_renderer_emits_deterministic_data_only_cpp() {
        let plan = render(&ir_from(RICH_SOURCE));
        let header = generated_text(&plan, "clapgen_metadata.hpp");
        let source = generated_text(&plan, "clapgen_metadata.cpp");

        assert!(header.starts_with("// Generated by clap-gen. DO NOT EDIT.\n"), "{header}");
        assert!(source.starts_with("// Generated by clap-gen. DO NOT EDIT.\n"), "{source}");
        assert!(header.contains("#include <clap/ext/params.h>"), "{header}");
        assert!(!header.contains("clap/ext/state.h"), "{header}");
        assert!(header.contains("struct PluginMetadata"), "{header}");
        assert!(header.contains("struct ParameterMetadata"), "{header}");
        assert!(header.contains("struct AudioPortMetadata"), "{header}");
        assert!(header.contains("struct NotePortMetadata"), "{header}");
        assert!(header.contains("struct StateFieldMetadata"), "{header}");
        assert!(header.contains("struct GuiApiMetadata"), "{header}");
        assert!(header.contains("struct PresetLocationMetadata"), "{header}");
        assert!(header.contains("struct PresetFormatMetadata"), "{header}");
        assert!(header.contains("struct FactoryMetadata"), "{header}");
        assert!(source.contains("com.example.codegen"), "{source}");
        assert!(source.contains("Codegen \\\"Unit\\\""), "{source}");
        assert!(source.contains("Example\\\\Labs"), "{source}");
        assert!(source.contains("gain"), "{source}");
        assert!(source.contains("main-in"), "{source}");
        assert!(source.contains("notes"), "{source}");
        assert!(source.contains("mode"), "{source}");

        for forbidden in ["clap_entry", "get_extension", "activate(", "process(", "plugin_factory"] {
            assert!(!header.contains(forbidden), "unexpected `{forbidden}` in header:\n{header}");
            assert!(!source.contains(forbidden), "unexpected `{forbidden}` in source:\n{source}");
        }
        for nondeterministic in ["Generated at", "timestamp", "hostname", "pid="] {
            assert!(!header.contains(nondeterministic), "{header}");
            assert!(!source.contains(nondeterministic), "{source}");
        }
    }

    #[test]
    fn adding_params_capability_changes_only_metadata_surfaces() {
        let base = render(&ir_from(SOURCE));
        let with_params = render(&ir_from(&SOURCE.replace(
            "extensions {}",
            "extensions { enable \"clap.params\" }",
        )));

        let changed = base
            .files
            .iter()
            .zip(&with_params.files)
            .filter_map(|(before, after)| (before.bytes != after.bytes).then_some(before.path))
            .collect::<Vec<_>>();
        assert_eq!(changed, ["clapgen_metadata.cpp", "clapgen_metadata.hpp"]);

        let base_header = generated_text(&base, "clapgen_metadata.hpp");
        let params_header = generated_text(&with_params, "clapgen_metadata.hpp");
        assert!(!base_header.contains("clap/ext/params.h"), "{base_header}");
        assert!(params_header.contains("#include <clap/ext/params.h>"), "{params_header}");
    }
}
