const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header() -> String {
    let mut output = String::from(BANNER);
    output.push_str(
        "#pragma once\n\n\
#include <clap/clap.h>\n\
#include <concepts>\n\
#include <cstdint>\n\n\
namespace clapgen::generated {\n\n\
template <typename Processor>\n\
concept NativeProcessor = requires(\n\
    Processor& processor,\n\
    double sample_rate,\n\
    std::uint32_t min_frames,\n\
    std::uint32_t max_frames,\n\
    const clap_process_t* process) {\n\
    { processor.init() } -> std::same_as<bool>;\n\
    { processor.activate(sample_rate, min_frames, max_frames) } -> std::same_as<bool>;\n\
    { processor.deactivate() } -> std::same_as<void>;\n\
    { processor.start_processing() } -> std::same_as<bool>;\n\
    { processor.stop_processing() } -> std::same_as<void>;\n\
    { processor.reset() } -> std::same_as<void>;\n\
    { processor.process(process) } -> std::same_as<clap_process_status>;\n\
};\n\n\
} // namespace clapgen::generated\n",
    );
    output
}
