const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header() -> String {
    let mut output = String::from(BANNER);
    output.push_str(
        "#pragma once\n\n\
#include <clap/clap.h>\n\
#include <cstdint>\n\n\
namespace clapgen::generated {\n\n\
// Borrowed callback lifetime:\n\
// clap_process_t and its nested event lists and audio buffers are host-owned.\n\
// These callback-scoped pointers must not be retained after Processor::process() returns.\n\n\
template <typename Processor>\n\
concept StateLoadedHookSafe =\n\
    (!requires(Processor& processor) { processor.on_state_loaded(); }) ||\n\
    requires(Processor& processor) { { processor.on_state_loaded() } noexcept; };\n\n\
template <typename Processor>\n\
concept NativeProcessor = StateLoadedHookSafe<Processor> && requires {\n\
    static_cast<bool (Processor::*)()>(&Processor::init);\n\
    static_cast<bool (Processor::*)(double, std::uint32_t, std::uint32_t)>(&Processor::activate);\n\
    static_cast<void (Processor::*)()>(&Processor::deactivate);\n\
    static_cast<bool (Processor::*)()>(&Processor::start_processing);\n\
    static_cast<void (Processor::*)()>(&Processor::stop_processing);\n\
    static_cast<void (Processor::*)()>(&Processor::reset);\n\
    static_cast<clap_process_status (Processor::*)(const clap_process_t*)>(&Processor::process);\n\
};\n\n\
} // namespace clapgen::generated\n",
    );
    output
}
