use std::fmt::Write as _;

use crate::ir::CanonicalIr;

const BANNER: &str = "// Generated by clap-gen. DO NOT EDIT.\n";

pub(crate) fn header(ir: &CanonicalIr) -> String {
    let mut resources = ir.resources().iter().collect::<Vec<_>>();
    resources.sort_by(|left, right| (&left.path, &left.mime).cmp(&(&right.path, &right.mime)));

    let mut output = String::from(BANNER);
    output.push_str(
        "#pragma once\n\n#include <array>\n\nnamespace clapgen::generated {\n\n\
struct ResourceMetadata {\n\
    const char* path;\n\
    const char* mime;\n\
};\n\n",
    );
    writeln!(
        &mut output,
        "inline constexpr std::array<ResourceMetadata, {}> resources{{{{",
        resources.len()
    )
    .expect("writing to String cannot fail");
    for resource in resources {
        writeln!(
            &mut output,
            "    ResourceMetadata{{{}, {}}},",
            cpp_string(&resource.path),
            optional_cpp_string(resource.mime.as_deref())
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("}};\n\n} // namespace clapgen::generated\n");
    output
}

fn optional_cpp_string(value: Option<&str>) -> String {
    value.map_or_else(|| "nullptr".to_owned(), cpp_string)
}

fn cpp_string(value: &str) -> String {
    let mut output = String::with_capacity(value.len() + 2);
    output.push('"');
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            '\u{0008}' => output.push_str("\\b"),
            '\u{000C}' => output.push_str("\\f"),
            character if character.is_control() && u32::from(character) <= 0o377 => {
                write!(&mut output, "\\{:03o}", u32::from(character))
                    .expect("writing to String cannot fail");
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}
