use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::ir::build_ir;
use crate::metadata::parse_metadata;

use super::{GenerationPlan, OUTPUT_NAMES, render};

const SOURCE: &str = "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen\" vendor=\"Example\" version=\"1.0.0\"\nprocessor class=\"CodegenProcessor\"\nparameters {}\naudio-ports {}\nnote-ports {}\nstate {}\ngui {}\npresets {}\nfactories {}\nextensions {}\n";

const RICH_SOURCE: &str = "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen \\\"Unit\\\"\" vendor=\"Example\\\\Labs\" version=\"1.0.0\"\nprocessor class=\"CodegenProcessor\" features=\"instrument,synthesizer\"\nparameters { param \"Gain\" id=\"gain\" min=0 max=1 default=0.5 flags=\"automatable\" unit=\"dB\" }\naudio-ports { input \"Main In\" id=\"main-in\" channels=2 flags=\"main\"; output \"Main Out\" id=\"main-out\" channels=2 flags=\"main\" }\nnote-ports { input \"Notes\" id=\"notes\" dialects=\"clap,midi\" preferred=\"clap\" }\nstate { field \"mode\" type=\"integer\" default=0 tag=\"mode\" }\ngui {}\npresets {}\nfactories {}\nextensions { enable \"clap.params\" }\n";

const RESOURCE_SOURCE: &str = "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen\" vendor=\"Example\" version=\"1.0.0\"\nprocessor class=\"CodegenProcessor\"\nparameters {}\naudio-ports {}\nnote-ports {}\nstate {}\ngui {\n    resource \"assets/panel.svg\" mime=\"image/svg+xml\"\n}\npresets {}\nfactories {}\nextensions {}\n";

fn ir_from(source: &str) -> crate::ir::CanonicalIr {
    ir_from_at(Path::new("plugin.kdl"), source)
}

fn ir_from_at(path: &Path, source: &str) -> crate::ir::CanonicalIr {
    let metadata = parse_metadata(path, source).expect("metadata should parse");
    build_ir(path, source, &metadata).expect("canonical IR should build")
}

fn build_file(path: &Path) -> crate::ir::CanonicalIr {
    let source = fs::read_to_string(path).expect("metadata should be readable");
    ir_from_at(path, &source)
}

fn relative_temporary_directory(name: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after epoch")
        .as_nanos();
    PathBuf::from("target").join(format!("clapgen-{name}-{}-{nonce}", std::process::id()))
}

fn generated_text<'a>(plan: &'a GenerationPlan, path: &str) -> &'a str {
    let file = plan.files.iter().find(|file| file.path == path).expect("generated file");
    std::str::from_utf8(&file.bytes).expect("generated files must be UTF-8")
}

#[test]
fn fixed_output_contract_is_stable() {
    assert_eq!(
        OUTPUT_NAMES,
        &[
            "clapgen.d",
            "clapgen.manifest.kdl",
            "clapgen.sources.kdl",
            "clapgen_ids.hpp",
            "clapgen_metadata.cpp",
            "clapgen_metadata.hpp",
            "clapgen_processor.hpp",
            "clapgen_resources.hpp",
        ]
    );
    assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("entry")));
    assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("factory")));
    assert!(OUTPUT_NAMES.iter().all(|name| !name.contains("plugin.cpp")));
}

#[test]
fn canonical_ir_renders_to_a_pure_deterministic_plan() {
    let ir = ir_from(SOURCE);
    let first = render(&ir);
    let second = render(&ir);
    let paths = first.files.iter().map(|file| file.path).collect::<Vec<_>>();

    assert_eq!(first, second);
    assert_eq!(paths.as_slice(), OUTPUT_NAMES);
}

#[test]
fn metadata_cpp_matches_the_golden_file() {
    let plan = render(&ir_from(SOURCE));
    assert_eq!(
        include_str!("../../tests/golden/issue37-metadata.cpp"),
        generated_text(&plan, "clapgen_metadata.cpp")
    );
}

#[test]
fn metadata_renderer_emits_deterministic_data_only_cpp() {
    let plan = render(&ir_from(RICH_SOURCE));
    let header = generated_text(&plan, "clapgen_metadata.hpp");
    let source = generated_text(&plan, "clapgen_metadata.cpp");

    assert!(header.starts_with("// Generated by clap-gen. DO NOT EDIT.\n"), "{header}");
    assert!(source.starts_with("// Generated by clap-gen. DO NOT EDIT.\n"), "{source}");
    assert!(header.contains("#include <clap/ext/params.h>"), "{header}");
    assert!(!header.contains("clap/ext/state.h"), "{header}");
    assert!(header.contains("struct PluginMetadata"), "{header}");
    assert!(header.contains("struct ParameterMetadata"), "{header}");
    assert!(header.contains("struct AudioPortMetadata"), "{header}");
    assert!(header.contains("struct NotePortMetadata"), "{header}");
    assert!(header.contains("struct StateFieldMetadata"), "{header}");
    assert!(header.contains("struct GuiApiMetadata"), "{header}");
    assert!(header.contains("struct PresetLocationMetadata"), "{header}");
    assert!(header.contains("struct PresetFormatMetadata"), "{header}");
    assert!(header.contains("struct FactoryMetadata"), "{header}");
    assert!(source.contains("com.example.codegen"), "{source}");
    assert!(source.contains("Codegen \\\"Unit\\\""), "{source}");
    assert!(source.contains("Example\\\\Labs"), "{source}");
    assert!(source.contains("gain"), "{source}");
    assert!(source.contains("main-in"), "{source}");
    assert!(source.contains("notes"), "{source}");
    assert!(source.contains("mode"), "{source}");

    for forbidden in ["clap_entry", "get_extension", "activate(", "process(", "plugin_factory"] {
        assert!(!header.contains(forbidden), "unexpected `{forbidden}` in header:\n{header}");
        assert!(!source.contains(forbidden), "unexpected `{forbidden}` in source:\n{source}");
    }
    for nondeterministic in ["Generated at", "timestamp", "hostname", "pid="] {
        assert!(!header.contains(nondeterministic), "{header}");
        assert!(!source.contains(nondeterministic), "{source}");
    }
}

#[test]
fn adding_params_capability_changes_only_expected_surfaces() {
    let base = render(&ir_from(SOURCE));
    let with_params =
        render(&ir_from(&SOURCE.replace("extensions {}", "extensions { enable \"clap.params\" }")));

    let changed = base
        .files
        .iter()
        .zip(&with_params.files)
        .filter_map(|(before, after)| (before.bytes != after.bytes).then_some(before.path))
        .collect::<Vec<_>>();
    assert_eq!(changed, ["clapgen.sources.kdl", "clapgen_metadata.cpp", "clapgen_metadata.hpp"]);

    let base_header = generated_text(&base, "clapgen_metadata.hpp");
    let params_header = generated_text(&with_params, "clapgen_metadata.hpp");
    assert!(!base_header.contains("clap/ext/params.h"), "{base_header}");
    assert!(params_header.contains("#include <clap/ext/params.h>"), "{params_header}");
    let params_sources = generated_text(&with_params, "clapgen.sources.kdl");
    assert!(params_sources.contains("key=\"extension:clap.params\""), "{params_sources}");
}

#[test]
fn resource_metadata_and_source_map_match_golden_files() {
    let plan = render(&ir_from(RESOURCE_SOURCE));
    let resources = generated_text(&plan, "clapgen_resources.hpp");
    let sources = generated_text(&plan, "clapgen.sources.kdl");

    assert_eq!(include_str!("../../tests/golden/issue38-resources.hpp"), resources);
    assert_eq!(include_str!("../../tests/golden/issue38-sources.kdl"), sources);
    kdl::KdlDocument::parse_v2(sources).expect("source map must remain valid KDL 2.0");
}

#[test]
fn resource_rendering_never_reads_or_modifies_user_resource_bytes() {
    let directory = relative_temporary_directory("issue38-resource-ownership");
    let assets = directory.join("assets");
    fs::create_dir_all(&assets).expect("assets directory");
    let resource = assets.join("panel.svg");
    let original = [0_u8, 0xff, 0x7f, b'<', b's', b'v', b'g', b'>'];
    fs::write(&resource, original).expect("resource should be writable");
    let manifest = directory.join("plugin.kdl");
    fs::write(&manifest, RESOURCE_SOURCE).expect("manifest should be writable");

    let ir = build_file(&manifest);
    let first = render(&ir);
    let second = render(&ir);
    let resources = generated_text(&first, "clapgen_resources.hpp");

    assert_eq!(first, second);
    assert_eq!(original.as_slice(), fs::read(&resource).expect("resource should be readable"));
    assert!(resources.contains("assets/panel.svg"), "{resources}");
    assert!(resources.contains("image/svg+xml"), "{resources}");
    assert!(!resources.contains("<svg>"), "resource bytes must never be embedded: {resources}");

    fs::remove_dir_all(directory).expect("temporary directory should be removable");
}

#[test]
fn imported_semantic_nodes_keep_relative_provenance_in_source_map() {
    let directory = relative_temporary_directory("issue38-imported-sources");
    let config = directory.join("config");
    let shared = directory.join("shared");
    fs::create_dir_all(&config).expect("config directory");
    fs::create_dir_all(&shared).expect("shared directory");
    fs::write(
        shared.join("common.kdl"),
        "clapgen schema=\"1.0.0\"\nparameters {\n    param \"Shared\" id=\"shared\" min=0 max=1 default=0.5\n}\ngui {\n    resource \"../assets/shared.svg\" mime=\"image/svg+xml\"\n}\n",
    )
    .expect("shared metadata");
    let manifest = config.join("plugin.kdl");
    fs::write(
        &manifest,
        "clapgen schema=\"1.0.0\"\nplugin id=\"com.example.codegen\" name=\"Codegen\" vendor=\"Example\" version=\"1.0.0\"\nprocessor class=\"CodegenProcessor\"\nimport \"../shared/common.kdl\"\nparameters {}\naudio-ports {}\nnote-ports {}\nstate {}\ngui {}\npresets {}\nfactories {}\nextensions {}\n",
    )
    .expect("root metadata");

    let plan = render(&build_file(&manifest));
    let sources = generated_text(&plan, "clapgen.sources.kdl");
    let imported_path = shared.join("common.kdl").to_string_lossy().replace('\\', "/");
    let current_directory =
        std::env::current_dir().expect("current directory").to_string_lossy().replace('\\', "/");

    kdl::KdlDocument::parse_v2(sources).expect("source map must remain valid KDL 2.0");
    assert!(
        sources.contains(&format!(
            "key=\"parameter:shared\" path=\"{imported_path}\" line=3 column=5"
        )),
        "{sources}"
    );
    assert!(
        sources.contains(&format!(
            "key=\"resource:../assets/shared.svg\" path=\"{imported_path}\" line=6 column=5"
        )),
        "{sources}"
    );
    assert!(!sources.contains(&current_directory), "absolute machine path leaked:\n{sources}");

    let parameter = sources.find("key=\"parameter:shared\"").expect("parameter entry");
    let plugin = sources.find("key=\"plugin\"").expect("plugin entry");
    let processor = sources.find("key=\"processor\"").expect("processor entry");
    let resource = sources.find("key=\"resource:../assets/shared.svg\"").expect("resource entry");
    assert!(parameter < plugin && plugin < processor && processor < resource, "{sources}");

    fs::remove_dir_all(directory).expect("temporary directory should be removable");
}

#[test]
fn source_map_escapes_semantic_keys_as_valid_kdl_strings() {
    let source = RESOURCE_SOURCE.replace("assets/panel.svg", "assets/panel \\\"front\\\".svg");
    let plan = render(&ir_from(&source));
    let sources = generated_text(&plan, "clapgen.sources.kdl");

    kdl::KdlDocument::parse_v2(sources).expect("escaped source map must parse as KDL 2.0");
    assert!(sources.contains("resource:assets/panel \\\"front\\\".svg"), "{sources}");
}
