// Generated by clap-gen. DO NOT EDIT.
#pragma once

#include <clap/clap.h>
#include <cstdint>

namespace clapgen::generated {

inline constexpr const char* const plugin_features_0[] = {
    nullptr,
};

inline constexpr clap_plugin_descriptor_t plugin_descriptor_0{
    .clap_version = CLAP_VERSION,
    .id = "com.example.alpha",
    .name = "Alpha",
    .vendor = "Example",
    .url = nullptr,
    .manual_url = nullptr,
    .support_url = nullptr,
    .version = "1.0.0",
    .description = nullptr,
    .features = plugin_features_0,
};

inline constexpr const char* const plugin_features_1[] = {
    nullptr,
};

inline constexpr clap_plugin_descriptor_t plugin_descriptor_1{
    .clap_version = CLAP_VERSION,
    .id = "com.example.fail",
    .name = "Fail",
    .vendor = "Example",
    .url = nullptr,
    .manual_url = nullptr,
    .support_url = nullptr,
    .version = "1.0.0",
    .description = nullptr,
    .features = plugin_features_1,
};

inline constexpr const char* const plugin_features_2[] = {
    nullptr,
};

inline constexpr clap_plugin_descriptor_t plugin_descriptor_2{
    .clap_version = CLAP_VERSION,
    .id = "com.example.zeta",
    .name = "Zeta",
    .vendor = "Example",
    .url = nullptr,
    .manual_url = nullptr,
    .support_url = nullptr,
    .version = "1.0.0",
    .description = nullptr,
    .features = plugin_features_2,
};

inline constexpr const clap_plugin_descriptor_t* const plugin_descriptors[] = {
    &plugin_descriptor_0,
    &plugin_descriptor_1,
    &plugin_descriptor_2,
};
inline constexpr std::uint32_t plugin_descriptor_count = 3u;

} // namespace clapgen::generated
