use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::thread;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

const OUTPUTS: &[&str] = &[
    "clapgen_plugin.hpp",
    "clapgen_plugin.cpp",
    "clapgen_resources.hpp",
    "clapgen.d",
    "clapgen_sources.map",
    "clapgen-manifest.kdl",
];

fn temporary_directory(label: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after epoch")
        .as_nanos();
    env::temp_dir().join(format!("clapgen-issue7-{label}-{}-{nonce}", std::process::id()))
}

fn manifest(extension: &str) -> String {
    format!(
        "clapgen schema=\"1.0.0\"\n\
plugin id=\"com.example.codegen\" name=\"Codegen\" vendor=\"Example\" version=\"1.0.0\"\n\
processor class=\"CodegenProcessor\"\n\
parameters {{ param \"Gain\" id=\"gain\" min=0.0 max=1.0 default=0.5 flags=\"automatable\" }}\n\
audio-ports {{ output \"Main\" id=\"main-out\" channels=2 flags=\"main\" }}\n\
note-ports {{}}\n\
state {{}}\n\
gui {{ resource \"panel.html\" mime=\"text/html\" }}\n\
presets {{}}\n\
factories {{}}\n\
extensions {{ enable \"{extension}\" }}\n"
    )
}

fn run_generate(metadata: &Path, out: &Path) -> Output {
    Command::new(env!("CARGO_BIN_EXE_clapgen"))
        .arg("generate")
        .arg("--metadata")
        .arg(metadata)
        .arg("--out")
        .arg(out)
        .output()
        .expect("clapgen generate should run")
}

fn read_outputs(out: &Path) -> BTreeMap<&'static str, Vec<u8>> {
    OUTPUTS
        .iter()
        .copied()
        .map(|name| (name, fs::read(out.join(name)).expect("generated output should be readable")))
        .collect()
}

#[test]
fn generate_produces_fixed_deterministic_build_products_without_touching_user_sources() {
    let directory = temporary_directory("deterministic");
    let source_dir = directory.join("src");
    let out = directory.join("build");
    fs::create_dir_all(&source_dir).expect("source directory");
    fs::create_dir_all(&out).expect("build directory");

    let metadata = source_dir.join("plugin.kdl");
    let resource = source_dir.join("panel.html");
    let processor = source_dir.join("CodegenProcessor.cpp");
    fs::write(&metadata, manifest("clap.params")).expect("metadata");
    fs::write(&resource, "<main>panel</main>\n").expect("resource");
    fs::write(&processor, "// user-owned processor\n").expect("processor");

    let first = run_generate(&metadata, &out);
    assert!(first.status.success(), "{}", String::from_utf8_lossy(&first.stderr));
    let first_bytes = read_outputs(&out);
    let first_times = OUTPUTS
        .iter()
        .copied()
        .map(|name| {
            (
                name,
                fs::metadata(out.join(name))
                    .expect("generated metadata")
                    .modified()
                    .expect("generated mtime"),
            )
        })
        .collect::<BTreeMap<_, _>>();

    thread::sleep(Duration::from_millis(1200));
    let second = run_generate(&metadata, &out);
    assert!(second.status.success(), "{}", String::from_utf8_lossy(&second.stderr));
    assert_eq!(first_bytes, read_outputs(&out), "no-op generation must be byte-identical");
    for name in OUTPUTS {
        let modified = fs::metadata(out.join(name))
            .expect("generated metadata")
            .modified()
            .expect("generated mtime");
        assert_eq!(first_times[name], modified, "unchanged output timestamp churned: {name}");
    }

    let header = String::from_utf8(first_bytes["clapgen_plugin.hpp"].clone()).expect("header utf8");
    assert!(header.contains("Generated by clap-gen; DO NOT EDIT."), "{header}");
    assert!(header.contains("#include <clap/ext/params.h>"), "{header}");
    assert!(!header.contains("#include <clap/ext/state.h>"), "{header}");
    assert!(header.contains("CodegenProcessor"), "{header}");

    let resources =
        String::from_utf8(first_bytes["clapgen_resources.hpp"].clone()).expect("resources utf8");
    assert!(resources.contains("panel.html"), "{resources}");

    let depfile = String::from_utf8(first_bytes["clapgen.d"].clone()).expect("depfile utf8");
    assert!(depfile.contains("plugin.kdl"), "{depfile}");
    assert!(depfile.contains("panel.html"), "{depfile}");

    let source_map =
        String::from_utf8(first_bytes["clapgen_sources.map"].clone()).expect("source map utf8");
    assert!(source_map.contains("parameter:gain"), "{source_map}");
    assert!(source_map.contains("plugin.kdl"), "{source_map}");

    let generation_manifest =
        String::from_utf8(first_bytes["clapgen-manifest.kdl"].clone()).expect("manifest utf8");
    assert!(generation_manifest.starts_with("generation version=1\n"), "{generation_manifest}");
    for name in OUTPUTS.iter().copied().filter(|name| *name != "clapgen-manifest.kdl") {
        assert!(generation_manifest.contains(name), "missing {name}: {generation_manifest}");
    }

    assert_eq!(
        "// user-owned processor\n",
        fs::read_to_string(&processor).expect("processor remains readable")
    );
    assert!(!out.join("CodegenProcessor.cpp").exists(), "generate must not synthesize user DSP");

    fs::remove_dir_all(directory).expect("temporary directory should be removed");
}

#[test]
fn changing_one_capability_only_changes_capability_dependent_surfaces() {
    let directory = temporary_directory("minimal-capability");
    let source_dir = directory.join("src");
    let out_params = directory.join("build-params");
    let out_state = directory.join("build-state");
    fs::create_dir_all(&source_dir).expect("source directory");
    fs::write(source_dir.join("panel.html"), "panel\n").expect("resource");

    let metadata = source_dir.join("plugin.kdl");
    fs::write(&metadata, manifest("clap.params")).expect("params metadata");
    let params = run_generate(&metadata, &out_params);
    assert!(params.status.success(), "{}", String::from_utf8_lossy(&params.stderr));

    fs::write(&metadata, manifest("clap.state")).expect("state metadata");
    let state = run_generate(&metadata, &out_state);
    assert!(state.status.success(), "{}", String::from_utf8_lossy(&state.stderr));

    let params_outputs = read_outputs(&out_params);
    let state_outputs = read_outputs(&out_state);
    let params_header =
        String::from_utf8(params_outputs["clapgen_plugin.hpp"].clone()).expect("params header");
    let state_header =
        String::from_utf8(state_outputs["clapgen_plugin.hpp"].clone()).expect("state header");
    assert!(params_header.contains("#include <clap/ext/params.h>"), "{params_header}");
    assert!(!params_header.contains("#include <clap/ext/state.h>"), "{params_header}");
    assert!(state_header.contains("#include <clap/ext/state.h>"), "{state_header}");
    assert!(!state_header.contains("#include <clap/ext/params.h>"), "{state_header}");

    assert_eq!(params_outputs["clapgen_resources.hpp"], state_outputs["clapgen_resources.hpp"]);
    assert_eq!(params_outputs["clapgen.d"], state_outputs["clapgen.d"]);

    fs::remove_dir_all(directory).expect("temporary directory should be removed");
}

#[test]
fn generation_preflight_failure_leaves_previous_output_set_untouched() {
    let directory = temporary_directory("transaction");
    let source_dir = directory.join("src");
    let out = directory.join("build");
    fs::create_dir_all(&source_dir).expect("source directory");
    fs::write(source_dir.join("panel.html"), "panel\n").expect("resource");
    let metadata = source_dir.join("plugin.kdl");
    fs::write(&metadata, manifest("clap.params")).expect("metadata");

    let first = run_generate(&metadata, &out);
    assert!(first.status.success(), "{}", String::from_utf8_lossy(&first.stderr));
    let before = fs::read(out.join("clapgen_plugin.hpp")).expect("existing header");

    fs::remove_file(out.join("clapgen_resources.hpp")).expect("remove generated resource table");
    fs::create_dir(out.join("clapgen_resources.hpp")).expect("blocking destination directory");
    fs::write(&metadata, manifest("clap.state")).expect("changed metadata");

    let failed = run_generate(&metadata, &out);
    assert!(!failed.status.success(), "generation should reject a non-file destination");
    assert_eq!(before, fs::read(out.join("clapgen_plugin.hpp")).expect("header after failure"));

    fs::remove_dir_all(directory).expect("temporary directory should be removed");
}
